version: '3'

services:
  php:
    env_file:
      - ../../../.env
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/laravel/public
      AUTORUN: 1
    build:
      context: ../../../.
      dockerfile: ./docker_setup/developer/mysql-laravel/Dockerfile
    container_name: laravel_server
    volumes:
      - ../../../.:/var/www/laravel
    ports:
      - "9000:80"
volumes:
  dbdata:
