version: '3'

services:
  php:
    env_file:
      - ../../../.env
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/laravel/public
      AUTORUN: 1
    build:
      context: ../../../.
      args:
        - NODE_VERSION=18.17.0
      dockerfile: ./docker_setup/developer/laravel-vite/Dockerfile
    container_name: laravel-vite_server
    volumes:
      - ../../../.:/var/www/laravel
    ports:
      - "9000:80"
      - "3000:3000"
      - "5173:5173"
volumes:
  dbdata:
